version: "3"

services:
  backend:
    build:
      context: ../rokket-api
      dockerfile: Dockerfile
    image: rokket-api
    container_name: rokket-api
    restart: always
    ports:
      - "80:8080"
    environment:
      - ROKKET_DB_HOST=mongo
      - ROKKET_DB_PORT=27017

  mongo:
    image: mongo
    container_name: rokket-db
    expose:
      - "27017"
