export const SET_BOOKS_FILTER = "SET_BOOKS_FILTER";

export const BookFilters = {
  READING_FILTER: "READING_FILTER",
  WISHING_FILTER: "WISHING_FILTER",
  FINISHED_FILTER: "FINISHED_FILTER",
  ALL_BOOKS_FILTER: "ALL_BOOK_FILTER",
};
